Language: zh-CN

Game:
  FoodPercentage: 0.05
  MaxMoveTools: 30
  ToolsPerFood: 5
  InitialTools: 10

Sound:
  PlayEatSound: true
  PlayLossSound: true
  PlayCountDownSound: true

Command:
  #  WinCommand: give [player] diamond 1
  WinCommand: [null]
  #  LossCommand: kill [player]
  LossCommand: [null]
